/*
 *
 */
SELECT DTC.OWNER
      ,DTC.TABLE_NAME
      ,DTC.COLUMN_NAME
      ,DTC.DATA_TYPE
      ,DTC.DATA_LENGTH
      ,DTC.DATA_SCALE
      ,DTC.DATA_PRECISION
      ,DTC.NULLABLE
      ,DTC.COLUMN_ID
FROM   DBA_TAB_COLUMNS DTC
WHERE  DTC.OWNER       LIKE NVL(:OWNER, DTC.OWNER)
AND    DTC.TABLE_NAME  LIKE NVL(:TABLE_NAME, DTC.TABLE_NAME)
AND    DTC.COLUMN_NAME LIKE NVL(:COLUMN_NAME, DTC.COLUMN_NAME)
ORDER BY DTC.OWNER
        ,DTC.TABLE_NAME
        ,DTC.COLUMN_ID
;
